#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx restart
